import { MotionExpression } from "../../MotionExpressionManager";
import * as THREE from "three";
import { VRMHumanBoneName, VRM } from "@pixiv/three-vrm";
import { BVH } from "three/examples/jsm/Addons.js";
import { convertBVHToVRMAnimation } from "./convertBvhToVrma";

export async function animationBvh2vrma(
  bvhObject: BVH,
  vrm: VRM,
  onProgress: (name: string, progress: number) => void
): Promise<string> {
  const buffer = await convertBVHToVRMAnimation(bvhObject);
  const blob = new Blob([buffer], { type: "model/gltf-binary" });
  const url = URL.createObjectURL(blob);
  return url;
}

const bvhVRMRigMap: { [animationBvhBoneName: string]: VRMHumanBoneName } = {
  "bones[Hips]": "hips",
  Hips: "hips",
  "bones[Spine]": "spine",
  Spine: "spine",
  "bones[Spine1]": "upperChest",
  Spine1: "upperChest",
  "bones[Neck]": "neck",
  Neck: "neck",
  "bones[Head]": "head",
  Head: "head",
  "bones[LeftShoulder]": "leftShoulder",
  LeftShoulder: "leftShoulder",
  "bones[LeftArm]": "leftUpperArm",
  LeftArm: "leftUpperArm",
  "bones[LeftForeArm]": "leftLowerArm",
  LeftForeArm: "leftLowerArm",
  "bones[LeftHand]": "leftHand",
  LeftHand: "leftHand",
  "bones[LThumb]": "leftThumbMetacarpal",
  LThumb: "leftThumbMetacarpal",
  // mixamorigLeftHandThumb2: 'leftThumbProximal',
  // mixamorigLeftHandThumb3: 'leftThumbDistal',
  // mixamorigLeftHandIndex1: 'leftIndexProximal',
  // mixamorigLeftHandIndex2: 'leftIndexIntermediate',
  // mixamorigLeftHandIndex3: 'leftIndexDistal',
  // mixamorigLeftHandMiddle1: 'leftMiddleProximal',
  // mixamorigLeftHandMiddle2: 'leftMiddleIntermediate',
  // mixamorigLeftHandMiddle3: 'leftMiddleDistal',
  // mixamorigLeftHandRing1: 'leftRingProximal',
  // mixamorigLeftHandRing2: 'leftRingIntermediate',
  // mixamorigLeftHandRing3: 'leftRingDistal',
  // mixamorigLeftHandPinky1: 'leftLittleProximal',
  // mixamorigLeftHandPinky2: 'leftLittleIntermediate',
  // mixamorigLeftHandPinky3: 'leftLittleDistal',
  "bones[RightShoulder]": "rightShoulder",
  RightShoulder: "rightShoulder",
  "bones[RightArm]": "rightUpperArm",
  RightArm: "rightUpperArm",
  "bones[RightForeArm]": "rightLowerArm",
  RightForeArm: "rightLowerArm",
  "bones[RightHand]": "rightHand",
  RightHand: "rightHand",
  // mixamorigRightHandPinky1: 'rightLittleProximal',
  // mixamorigRightHandPinky2: 'rightLittleIntermediate',
  // mixamorigRightHandPinky3: 'rightLittleDistal',
  // mixamorigRightHandRing1: 'rightRingProximal',
  // mixamorigRightHandRing2: 'rightRingIntermediate',
  // mixamorigRightHandRing3: 'rightRingDistal',
  // mixamorigRightHandMiddle1: 'rightMiddleProximal',
  // mixamorigRightHandMiddle2: 'rightMiddleIntermediate',
  // mixamorigRightHandMiddle3: 'rightMiddleDistal',
  // mixamorigRightHandIndex1: 'rightIndexProximal',
  // mixamorigRightHandIndex2: 'rightIndexIntermediate',
  // mixamorigRightHandIndex3: 'rightIndexDistal',
  "bones[RThumb]": "rightThumbMetacarpal",
  RThumb: "rightThumbMetacarpal",
  "bones[LeftUpLeg]": "leftUpperLeg",
  LeftUpLeg: "leftUpperLeg",
  "bones[LeftLeg]": "rightLowerLeg",
  LeftLeg: "rightLowerLeg",
  "bones[LeftFoot]": "leftFoot",
  LeftFoot: "leftFoot",
  "bones[LeftToeBase]": "leftToes",
  LeftToeBase: "leftToes",
  "bones[RightUpLeg]": "rightUpperLeg",
  RightUpLeg: "rightUpperLeg",
  "bones[RightLeg]": "rightLowerLeg",
  RightLeg: "rightLowerLeg",
  "bones[RightFoot]": "rightFoot",
  RightFoot: "rightFoot",
  "bones[RightToeBase]": "rightToes",
  RightToeBase: "rightToes",
};

// ( 62 )[
// 'bones[Hips]',
// 'bones[Hips]',
// 'bones[LHipJoint]',
// 'bones[LHipJoint]',
// 'bones[LeftUpLeg]',
// 'bones[LeftUpLeg]',
// 'bones[LeftLeg]',
// 'bones[LeftLeg]',
// 'bones[LeftFoot]',
// 'bones[LeftFoot]',
// 'bones[LeftToeBase]',
// 'bones[LeftToeBase]',
// 'bones[RHipJoint]',
// 'bones[RHipJoint]',
// 'bones[RightUpLeg]',
// 'bones[RightUpLeg]',
// 'bones[RightLeg]',
// 'bones[RightLeg]',
// 'bones[RightFoot]',
// 'bones[RightFoot]',
// 'bones[RightToeBase]',
// 'bones[RightToeBase]',
// 'bones[LowerBack]',
// 'bones[LowerBack]',
// 'bones[Spine]',
// 'bones[Spine]',
// 'bones[Spine1]',
// 'bones[Spine1]',
// 'bones[Neck]',
// 'bones[Neck]',
// 'bones[Neck1]',
// 'bones[Neck1]',
// 'bones[Head]',
// 'bones[Head]',
// 'bones[LeftShoulder]',
// 'bones[LeftShoulder]',
// 'bones[LeftArm]',
// 'bones[LeftArm]',
// 'bones[LeftForeArm]',
// 'bones[LeftForeArm]',
// 'bones[LeftHand]',
// 'bones[LeftHand]',
// 'bones[LeftFingerBase]',
// 'bones[LeftFingerBase]',
// 'bones[LFingers]',
// 'bones[LFingers]',
// 'bones[LThumb]',
// 'bones[LThumb]',
// 'bones[RightShoulder]',
// 'bones[RightShoulder]',
// 'bones[RightArm]',
// 'bones[RightArm]',
// 'bones[RightForeArm]',
// 'bones[RightForeArm]',
// 'bones[RightHand]',
// 'bones[RightHand]',
// 'bones[RightFingerBase]',
// 'bones[RightFingerBase]',
// 'bones[RFingers]',
// 'bones[RFingers]',
// 'bones[RThumb]',
// 'bones[RThumb]' ];
